<Project>
  <PropertyGroup>
    <Company>KRS</Company>
    <Authors>Руслан Керусов</Authors>
    <Copyright>Copyright © 2026 KRS. All rights reserved.</Copyright>
    <RepositoryUrl>https://github.com/jadieify-hub/esm-tspiot-multi-kkt-tool</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <PathMap>$(MSBuildThisFileDirectory)=/_/</PathMap>
  </PropertyGroup>
</Project>
